In [1]:
# importing the packages necesary

import torch
from torch import nn
import pandas as pd
import numpy as np

In [2]:
# building the model using torch

class FeedforwardModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        # self.flatten = nn.Flatten()

        # linear function
        self.model = nn.Linear(input_dim, output_dim)


    def forward(self, X):
        # X = self.flatten(X)
        out = self.model(X)
        return out

In [3]:
model = FeedforwardModel(input_dim = 1,  output_dim = 1)

In [25]:
# setting the parameters
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

## example of a formula it's trying to learn

$$
y = f(x;\theta)
$$

where $f(.)$ is $3.4x_1 + 2.5$


In [76]:
x = torch.rand(1000,1)
y = x * 3.4 + 2.5

data = torch.cat((x,y), 1)

In [77]:
# prepare the dataset

batch_size = 10
n_epochs = 100

train_loader = torch.utils.data.DataLoader(dataset = data,
                                           batch_size = 10,
                                           shuffle = True)

In [78]:
# n_epochs = 100

for epochs in range(n_epochs):
    for i, _data in enumerate(train_loader):

        _x = _data.T[0].reshape(-1, 1)
        _y = _data.T[-1].reshape(-1, 1)

        # zero the gradients
        optimizer.zero_grad()

        outputs = model(_x)
        loss = loss_fn(outputs, _y)

        loss.backward()

        optimizer.step()


In [79]:
model.state_dict()

OrderedDict([('model.weight', tensor([[3.4000]])),
             ('model.bias', tensor([2.5000]))])

In [72]:
_y

tensor([[3.3820],
        [4.6753],
        [5.4200],
        [4.0567],
        [4.7946],
        [3.7071],
        [5.2824],
        [2.7835],
        [5.3020],
        [5.3052]])

In [31]:
loss

tensor(0.1662, grad_fn=<MseLossBackward0>)

In [34]:
model.state_dict()

OrderedDict([('model.weight', tensor([[-0.0120]])),
             ('model.bias', tensor([0.3396]))])

In [ ]:
iter = 0
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Load images with gradient accumulation capabilities
        images = images.view(-1, 28*28).requires_grad_()

        # Clear gradients w.r.t. parameters
        optimizer.zero_grad()

        # Forward pass to get output/logits
        outputs = model(images)

        # Calculate Loss: softmax --> cross entropy loss
        loss = criterion(outputs, labels)

        # Getting gradients w.r.t. parameters
        loss.backward()

        # Updating parameters
        optimizer.step()

        iter += 1

        if iter % 500 == 0:
            # Calculate Accuracy
            correct = 0
            total = 0
            # Iterate through test dataset
            for images, labels in test_loader:
                # Load images with gradient accumulation capabilities
                images = images.view(-1, 28*28).requires_grad_()

                # Forward pass only to get logits/output
                outputs = model(images)

                # Get predictions from the maximum value
                _, predicted = torch.max(outputs.data, 1)

                # Total number of labels
                total += labels.size(0)

                # Total correct predictions
                correct += (predicted == labels).sum()

            accuracy = 100 * correct / total

            # Print Loss
            print('Iteration: {}. Loss: {}. Accuracy: {}'.format(iter, loss.item(), accuracy))

In [ ]:
model(x)

IndexError: ignored

In [ ]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
# x_train = x_train.reshape(-1, 1)

In [ ]:
x

tensor([[0.0821],
        [0.7113],
        [0.5737],
        [0.9840],
        [0.3461],
        [0.1524],
        [0.9278],
        [0.7602],
        [0.2953],
        [0.1989]])

In [ ]:
torch.from_numpy(x_train)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x.grad

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        # self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        # x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [ ]:
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
X = torch.rand(1, 28, 28)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

RuntimeError: ignored